// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/64626c83c9e71f8e85576bc9
###
GET http://localhost:8080/contacts/64626c98c9e71f8e85576bca
###
GET http://localhost:8080/contacts/646ccc90ce2128a4c8e6ddab

// PRODUCTION Deploy
###
GET https://cse341-palmer.onrender.com/contacts
###
GET https://cse341-palmer.onrender.com/contacts/64626c83c9e71f8e85576bc9
###
GET https://cse341-palmer.onrender.com/contacts/64626c98c9e71f8e85576bca
###
GET https://cse341-palmer.onrender.com/contacts/646ccc90ce2128a4c8e6ddab